global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using UniversityManagementBackend.Models;
global using UniversityManagementBackend.Dtos;
global using System.ComponentModel.DataAnnotations;
global using UniversityManagementBackend.Services;
global using UniversityManagementBackend.Interfaces;
global using UniversityManagementBackend.Data;
